name:                kern
version:             0.1.0.0
github:              "groutcho/kern"
license:             BSD3
author:              "Sébastien Guimmara"
maintainer:          "sguimmara@pobox.com"
copyright:           "2018 Sébastien Guimmara"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/groutcho/kern#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1.0
- text
- filepath

library:
  source-dirs: src

executables:
  kern:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kern

tests:
  kern-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kern
